/**
 * Base prompt template for Australian legal documents
 * Ensures all mandatory compliance clauses are included
 */

export interface PromptTemplate {
  documentType: string;
  buildPrompt(clientDetails: Record<string, any>, customRequirements?: string): string;
  validateClientDetails(clientDetails: Record<string, any>): string[];
}

export abstract class BasePromptTemplate implements PromptTemplate {
  abstract documentType: string;
  
  /**
   * Australian legal compliance clauses that must be included
   */
  protected static readonly MANDATORY_COMPLIANCE_CLAUSES = {
    SPAM_ACT_FOOTER: `

IMPORTANT COMPLIANCE NOTICE:
This document is generated by Legally Legit AI. In accordance with the Australian Spam Act 2003, this communication contains information about legal services. If you have received this document in error or no longer wish to receive communications from us, please contact us at support@legallyllegit.ai or unsubscribe at [unsubscribe link].

Our registered office is located at [Company Address], Australia. ABN: [Company ABN].
`,
    
    PRIVACY_ACT_CLAUSE: `
Privacy Notice: This document may contain personal information. In accordance with the Australian Privacy Act 1988, we are committed to protecting your privacy. For our full privacy policy, visit [privacy policy URL].
`,
    
    CONSUMER_LAW_DISCLAIMER: `
Australian Consumer Law Disclaimer: This document is provided for informational purposes only and does not constitute legal advice. You should seek independent legal advice regarding your specific circumstances. This service is provided subject to Australian Consumer Law protections.
`,
    
    PROFESSIONAL_INDEMNITY: `
Professional Standards: This document is generated using AI technology. While we strive for accuracy, you should have this document reviewed by a qualified Australian legal practitioner before relying on it for any legal matters.
`
  };

  /**
   * Common Australian business fields that should be validated
   */
  protected static readonly REQUIRED_AUSTRALIAN_FIELDS = [
    'businessName',
    'abn', // Australian Business Number
    'businessAddress',
    'state', // Australian state/territory
  ];

  /**
   * Build the complete prompt with compliance clauses
   */
  buildPrompt(clientDetails: Record<string, any>, customRequirements?: string): string {
    const basePrompt = this.buildBasePrompt(clientDetails, customRequirements);
    const complianceFooter = this.buildComplianceFooter();
    
    return `${basePrompt}

${complianceFooter}

CRITICAL INSTRUCTIONS:
1. This document MUST comply with Australian law
2. Include the provided compliance notices at the end of the document
3. Use Australian spelling and terminology throughout
4. Reference appropriate Australian legislation where applicable
5. Include proper date formatting (DD/MM/YYYY)
6. Use Australian currency (AUD) where monetary values are mentioned
7. Ensure all mandatory clauses are present and prominent`;
  }

  /**
   * Build the document-specific prompt (to be implemented by subclasses)
   */
  protected abstract buildBasePrompt(clientDetails: Record<string, any>, customRequirements?: string): string;

  /**
   * Build the compliance footer with all mandatory clauses
   */
  protected buildComplianceFooter(): string {
    return Object.values(BasePromptTemplate.MANDATORY_COMPLIANCE_CLAUSES).join('\n');
  }

  /**
   * Validate client details for Australian business requirements
   */
  validateClientDetails(clientDetails: Record<string, any>): string[] {
    const errors: string[] = [];
    
    // Check required fields
    for (const field of BasePromptTemplate.REQUIRED_AUSTRALIAN_FIELDS) {
      if (!clientDetails[field] || clientDetails[field].toString().trim() === '') {
        errors.push(`Missing required field: ${field}`);
      }
    }

    // Validate ABN format (11 digits)
    if (clientDetails.abn) {
      const abnPattern = /^\d{11}$/;
      if (!abnPattern.test(clientDetails.abn.toString().replace(/\s/g, ''))) {
        errors.push('ABN must be 11 digits');
      }
    }

    // Validate Australian state
    if (clientDetails.state) {
      const validStates = ['NSW', 'VIC', 'QLD', 'WA', 'SA', 'TAS', 'ACT', 'NT'];
      if (!validStates.includes(clientDetails.state.toUpperCase())) {
        errors.push('State must be a valid Australian state or territory');
      }
    }

    return errors;
  }

  /**
   * Format Australian address
   */
  protected formatAustralianAddress(address: any): string {
    if (typeof address === 'string') return address;
    
    const parts = [
      address.streetAddress,
      address.suburb,
      address.state,
      address.postcode
    ].filter(Boolean);
    
    return parts.join(', ');
  }

  /**
   * Format Australian currency
   */
  protected formatAustralianCurrency(amount: number): string {
    return new Intl.NumberFormat('en-AU', {
      style: 'currency',
      currency: 'AUD'
    }).format(amount);
  }

  /**
   * Format Australian date
   */
  protected formatAustralianDate(date: Date | string): string {
    const dateObj = typeof date === 'string' ? new Date(date) : date;
    return dateObj.toLocaleDateString('en-AU', {
      day: '2-digit',
      month: '2-digit',
      year: 'numeric'
    });
  }
}

/**
 * Utility function to get current date in Australian format
 */
export function getCurrentAustralianDate(): string {
  return new Date().toLocaleDateString('en-AU', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric'
  });
}

/**
 * Utility function to validate and format ABN
 */
export function formatABN(abn: string): string {
  const cleaned = abn.replace(/\s/g, '');
  if (cleaned.length !== 11) {
    throw new Error('ABN must be 11 digits');
  }
  return `${cleaned.slice(0, 2)} ${cleaned.slice(2, 5)} ${cleaned.slice(5, 8)} ${cleaned.slice(8)}`;
}
